### ISSUE TITLE
The INFINI Gateway Case Sharing: Use INFINI Gateway to access ECE instead of Nginx

### ISSUE THREAD

**Issue by liukuijun666** [liukuijun666/Blog#2]
## Background

A certain ECE cluster has more than 300 instances at the back end. Initially, Nginx + Keepalived was used to proxy requests and forward them to the ECE Proxy.

As the number of business requests increased, Nginx encountered anomalies and could no longer meet the requirements.

## Solution

Carry out the transformation of request proxying. In order to minimize significant changes to the existing network environment, the design scheme is as follows:

- Retain the current Nginx + Keepalived. The INFINI Gateway and Nginx are deployed on one machine in a mixed manner. Meanwhile, utilize Keepalived to ensure the high availability of the INFINI gateway.

- Replace the proxy function of Nginx that is used to handle business access. Let the INFINI Gateway undertake the external requests and forward them to the ECE Proxy at the back end.

The configuration of the INFINI Gateway is as follows:

```yaml
path.data: data
path.logs: log

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 10000
    network:
      binding: 0.0.0.0:9243
    tls:
      enabled: true
      cert_file: /etc/ssl.crt
      key_file: /etc/ssl.key
      skip_insecure_verify: false
flow:
  - name: primary-write-flow
    filter:
      - http:
          schema: "https" #https or http
          hosts:
            - "192.168.200.209:9243"
            - "192.168.200.210:9243"
            - "192.168.200.211:9243"
  - name: request_logging
    filter:
      - logging:
          queue_name: request_logging
          max_request_body_size: 10240
          max_response_body_size: 10240
          when: #>1s or none-200 requests will be logged
            or:
              - not:
                  or:
                    - equals:
                        _ctx.request.path: "/favicon.ico"
                    - equals:
                        _ctx.response.status: 200
                    - in:
                        _ctx.request.path: ["/sw.js"]
              - range:
                  _ctx.elapsed.gte: 1000
router:
  - name: my_router
    default_flow: primary-write-flow
    tracing_flow: request_logging

elasticsearch:
  - name: logging-server
    enabled: true
    endpoints:
      - https://d6794e84d46e4b7db21d364de10620c4.192.168.200.209.ip.es.io:9243
    basic_auth:
      username: elastic
      password: 1qaz!QAZ
    discovery:
      enabled: false

pipeline:
  - name: indexing_merge
    auto_start: true
    keep_running: true
    processor:
      - indexing_merge:
          input_queue: "request_logging"
          elasticsearch: "logging-server"
          index_name: "infini_gateway_requests"
          output_queue:
            name: "gateway_requests"
            label:
              tag: "request_logging"
          worker_size: 1
          bulk_size_in_mb: 10
  - name: logging_requests
    auto_start: true
    keep_running: true
    processor:
      - bulk_indexing:
          bulk:
            compress: true
            batch_size_in_mb: 10
            batch_size_in_docs: 5000
          consumer:
            fetch_max_messages: 100
          queues:
            type: indexing_merge
          when:
            cluster_available: [ "logging-server" ]
```

Configuration description:

```yaml
path.data: /data
path.logs: /log
```

- The local storage path of the INFINI gateway. It is recommended to configure an SSD with a disk space of more than 500GB.

```yaml
tls:
  enabled: true
  cert_file: /etc/ssl.crt
  key_file: /etc/ssl.key
```

- Wildcard domain name certificate, which should be kept consistent with that of Nginx.

```yaml
- http:
    schema: "https" #https or http
    hosts:
      - "192.168.200.209:9243"
      - "192.168.200.210:9243"
      - "192.168.200.211:9243"
```

- The access address of the ECE Proxy.

```yaml
- name: logging-server
  enabled: true
  endpoints:
    - https://d6794e84d46e4b7db21d364de10620c4.192.168.200.209.ip.es.io:9243
  basic_auth:
    username: elastic
    password: 1qaz!QAZ
```

- The cluster for recording access logs, which is used to analyze the requests sent to the Elasticsearch server.

For more configuration information about the INFINI Gateway, please refer to the [official website](https://infinilabs.cn/docs/latest/gateway/).

## About the INFINI Gateway

![](http://infinilabs.cn/img/blog/banner/gateway_banner@2x.png)

The INFINI Gateway is a high performance gateway for Elasticsearch. It offers a broad range of features and is easy to use. 
The INFINI Gateway works in the same way as a common reverse proxy. It is usually deployed in front of Elasticsearch clusters. All requests are sent to the gateway instead of Elasticsearch, and then the gateway forwards the requests to the back-end Elasticsearch clusters. The gateway is deployed between the client and Elasticsearch. Therefore, the gateway can be configured to perform index-level traffic control and throttling, cache acceleration for common queries, query request audit, and dynamic modification of query results.

The INFINI Gateway has been open-sourced now (https://github.com/infinilabs/gateway). If you have any related questions or suggestions, you are welcome to submit PRs or Issues and join in the open-source co-construction together!
