### ISSUE TITLE
The INFINI Gateway Case Sharing - Use the INFINI Gateway to accelerate the writing speed of indexes

### ISSUE THREAD

**Issue by liukuijun666** [liukuijun666/Blog#3]
## Background

The writing speed of certain business data is slow and needs to be increased.

## Solution

The design scheme is as follows:

- Transform the data writing into the form of bulk requests.

- The front gateway separates the bulk requests of the specified business and forwards them to the async gateway.

- The async gateway processes the bulk requests asynchronously.

### The Front Gateway

The configuration of the INFINI Gateway is as follows:

```yaml
path.data: data-front
path.logs: log-front

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 50000
    network:
      binding: :9243
    tls:
      enabled: true
      cert_file: /etc/ssl.crt
      key_file: /etc/ssl.key
      skip_insecure_verify: false

flow:
  - name: test-async-indexing
    filter:
      - elasticsearch:
          elasticsearch: test-es
      - flow:
          when:
            equals:
              _ctx.response.status: 0
          flows:
            - default-flow
      - drop:
  - name: bulk_flow
    filter:
      - flow:
          when:
            and:
              - contains:
                  _ctx.request.path: /_bulk
              - prefix:
                  _ctx.request.host: 165ed1e903914b929746c642d92b5a21
          flows:
            - test-async-indexing
      - flow:
          flows:
            - default-flow
  - name: default-flow
    filter:
      - http:
          schema: "https" #https or http
          max_idle_conn_duration: "900s"
          skip_failure_host: false
          hosts:
            - "192.168.200.209:9243"
            - "192.168.200.210:9243"
            - "192.168.200.211:9243"
  - name: drop_flow
    filter:
      - drop:
  - name: test-request_indexing
    filter:
      - ratio:
          ratio: 0.5
          flow: drop_flow
          continue: false
      - logging:
          queue_name: test-request_logging
          max_request_body_size: 4096
          max_response_body_size: 4096
      - drop:
  - name: request_logging
    filter:
      - flow:
          when:
            prefix:
              _ctx.request.host: 165ed1e903914b929746c642d92b5a21
          flows:
            - test-request_indexing
      - logging:
          queue_name: request_logging
          max_request_body_size: 4096
          max_response_body_size: 4096
          when: #>1s or none-200 requests will be logged
            or:
              - not:
                  or:
                    - equals:
                        _ctx.request.path: "/favicon.ico"
                    - in:
                        _ctx.response.status: [404, 200, 201]
                    - in:
                        _ctx.request.path: ["/sw.js"]
              - range:
                  _ctx.elapsed.gte: 1000
router:
  - name: my_router
    default_flow: default-flow
    tracing_flow: request_logging
    rules:
      - method:
          - "*"
        pattern:
          - "/_bulk"
          - "/{any_index}/_bulk"
        flow:
          - bulk_flow

elasticsearch:
  - name: logging-server
    enabled: true
    endpoints:
      - https://d6794e84d46e4b7db21d364de10620c4.192.168.200.209.ip.es.io:9243
    basic_auth:
      username: elastic
      password: 1qaz!QAZ
    discovery:
      enabled: false
  - name: test-logging-server
    enabled: true
    endpoints:
      - https://ccb82916fc594ccf94a241bba9a8d1b6.192.168.200.209.ip.es.io:9243
    basic_auth:
      username: elastic
      password: 1qaz!QAZ
    discovery:
      enabled: false
  - name: test-es
    enabled: true
    endpoints:
      - https://165ed1e903914b929746c642d92b5a21.192.168.3.185.async.vip:8000
    basic_auth:
      username: elastic
      password: 1qaz!QAZ
    discovery:
      enabled: false

pipeline:
  - name: metrics_ingest
    auto_start: true
    keep_running: true
    retry_delay_in_ms: 1000
    processor:
      - json_indexing:
          index_name: ".infini_metrics"
          elasticsearch: "logging-server"
          input_queue: "metrics"
          idle_timeout_in_seconds: 1
          worker_size: 1
          bulk_size_in_mb: 10 #in MB
          when:
            cluster_available: ["logging-server"]
  - name: indexing_merge
    auto_start: true
    keep_running: true
    processor:
      - indexing_merge:
          input_queue: "request_logging"
          elasticsearch: "logging-server"
          index_name: ".infini_requests_logging"
          output_queue:
            name: "gateway_requests"
            label:
              tag: "request_logging"
          worker_size: 1
          bulk_size_in_mb: 10
  - name: logging_requests
    auto_start: true
    keep_running: true
    processor:
      - bulk_indexing:
          bulk:
            compress: true
            batch_size_in_mb: 10
            batch_size_in_docs: 5000
            bulk_result_message_queue: ""
            response_handle:
              save_success_results: false
              output_bulk_stats: false
          queue_selector:
            labels:
              tag: request_logging
          consumer:
            fetch_max_messages: 100
          queues:
            type: indexing_merge
          when:
            cluster_available: ["logging-server"]
  - name: test-logging_requests
    auto_start: true
    keep_running: true
    processor:
      - bulk_indexing:
          bulk:
            compress: true
            batch_size_in_mb: 10
            batch_size_in_docs: 5000
            bulk_result_message_queue: ""
            response_handle:
              save_success_results: false
              output_bulk_stats: false
          queue_selector:
            labels:
              tag: test-request_logging
          consumer:
            fetch_max_messages: 100
          queues:
            type: indexing_merge
          when:
            cluster_available: ["test-logging-server"]
  - name: test_indexing_merge
    auto_start: true
    keep_running: true
    processor:
      - indexing_merge:
          input_queue: "test-request_logging"
          elasticsearch: "test-logging-server"
          index_name: ".infini_requests_logging"
          output_queue:
            name: "test-gateway_requests"
            label:
              tag: "test-request_logging"
          worker_size: 1
          bulk_size_in_mb: 10

metrics:
  enabled: true
  queue: metrics
  instance:
    enabled: true
  network:
    enabled: true
    summary: true

badger:
  value_log_max_entries: 1000000
  value_log_file_size: 104857600
```

Configuration description:

```yaml
- name: test-async-indexing
  filter:
    - elasticsearch:
        elasticsearch: test-es
    - flow:
        when:
          equals:
            _ctx.response.status: 0
        flows:
          - default-flow
    - drop:
- name: bulk_flow
  filter:
    - flow:
        when:
          and:
            - contains:
                _ctx.request.path: /_bulk
            - prefix:
                _ctx.request.host: 165ed1e903914b929746c642d92b5a21
        flows:
          - test-async-indexing
    - flow:
        flows:
          - default-flow
```

- Filter the specified requests into an independent processing flow according to the 'request.host' and 'request.path' in the request information.

```yaml
- name: test-request_indexing
  filter:
    - ratio:
        ratio: 0.5
        flow: drop_flow
        continue: false
    - logging:
        queue_name: test-request_logging
        max_request_body_size: 4096
        max_response_body_size: 4096
    - drop:
- name: request_logging
  filter:
    - flow:
        when:
          prefix:
            _ctx.request.host: 165ed1e903914b929746c642d92b5a21
        flows:
          - test-request_indexing
    - logging:
        queue_name: request_logging
        max_request_body_size: 4096
        max_response_body_size: 4096
        when: #>1s or none-200 requests will be logged
          or:
            - not:
                or:
                  - equals:
                      _ctx.request.path: "/favicon.ico"
                  - in:
                      _ctx.response.status: [404, 200, 201]
                  - in:
                      _ctx.request.path: ["/sw.js"]
            - range:
                _ctx.elapsed.gte: 1000
```

- The request records are also filtered into a separate processing flow according to the specified 'request.host'.

### The Async Gateway

The configuration of the INFINI Gateway is as follows:

```yaml
path.data: data-async
path.logs: log-async

pipeline:
  - name: metrics_merge
    auto_start: true
    keep_running: true
    processor:
      - indexing_merge:
          input_queue: "metrics"
          elasticsearch: "logging-server"
          index_name: ".infini_metrics"
          output_queue:
            name: "bulk_requests"
            label:
              tag: "metrics"
          worker_size: 1
          bulk_size_in_mb: 10
  - name: request_logging_merge
    auto_start: true
    keep_running: true
    processor:
      - indexing_merge:
          input_queue: "request_logging"
          elasticsearch: "logging-server"
          index_name: ".infini_requests_logging"
          output_queue:
            name: "bulk_requests"
            label:
              tag: "request_logging"
          worker_size: 1
          bulk_size_in_mb: 10
  - name: failure_message_merge
    auto_start: true
    keep_running: true
    processor:
      - indexing_merge:
          input_queue: "bulk_result_messages"
          elasticsearch: "logging-server"
          index_name: ".infini_async_bulk_results"
          output_queue:
            name: "bulk_requests"
            label:
              tag: "bulk_logging"
          worker_size: 1
          bulk_size_in_mb: 10
  - name: ingest_merged_requests
    auto_start: true
    keep_running: true
    processor:
      - bulk_indexing:
          bulk:
            compress: true
            batch_size_in_mb: 10
            batch_size_in_docs: 5000
            retry_rules:
              retry_429: true
              default: true
              retry_4xx: false
          consumer:
            fetch_max_messages: 100
          queues:
            type: indexing_merge
          when:
            cluster_available: ["logging-server"]
  - name: bulk_request_ingest
    auto_start: true
    keep_running: true
    retry_delay_in_ms: 1000
    processor:
      - bulk_indexing:
          max_connection_per_node: 1000
          num_of_slices: 2
          max_worker_size: 200
          idle_timeout_in_seconds: 3
          bulk:
            compress: false
            batch_size_in_mb: 20
            batch_size_in_docs: 5000
            dead_letter_queue: "bulk_dead_requests"
            bulk_result_message_queue: "bulk_result_messages"
            max_request_body_size: 10240
            max_response_body_size: 10240
            save_success_results: true
            retry_rules:
              denied:
                keyword:
                  - illegal_state_exception
          consumer:
            fetch_max_messages: 1000
            eof_retry_delay_in_ms: 500
          queue_selector:
            labels:
              type: bulk_reshuffle

entry:
  - name: my_es_entry
    enabled: true
    router: my_router
    max_concurrency: 200000
    network:
      binding: 0.0.0.0:8000
    tls:
      enabled: true
      cert_file: /etc/ssl.crt
      key_file: /etc/ssl.key
      skip_insecure_verify: false

flow:
  - name: async_bulk
    filter:
      - bulk_reshuffle:
          when:
            contains:
              _ctx.request.path: /_bulk
          elasticsearch: prod
          level: node
          partition_size: 1
          #shards: [1,3,5,7,9,11,13]
          continue_metadata_missing: true
          fix_null_id: true
      - http:
          schema: "https" #https or http
          hosts:
            - "165ed1e903914b929746c642d92b5a21.192.168.200.209.ip.es.a:9243"
            - "165ed1e903914b929746c642d92b5a21.192.168.200.209.ip.es.b:9243"
            - "165ed1e903914b929746c642d92b5a21.192.168.200.209.ip.es.c:9243"

router:
  - name: my_router
    default_flow: async_bulk

elasticsearch:
  - name: prod
    enabled: true
    endpoints:
      - https://165ed1e903914b929746c642d92b5a21.192.168.200.209.ip.es.a:9243
      - https://165ed1e903914b929746c642d92b5a21.192.168.200.209.ip.es.b:9243
      - https://165ed1e903914b929746c642d92b5a21.192.168.200.209.ip.es.c:9243
    discovery:
      enabled: false
    basic_auth:
      username: elastic
      password: 1qaz!QAZ
  - name: logging-server
    enabled: true
    endpoints:
      - https://ccb82916fc594ccf94a241bba9a8d1b6.192.168.200.209.ip.es.io:9243
    basic_auth:
      username: elastic
      password: 1qaz!QAZ
    discovery:
      enabled: false
    request_timeout: 60

elastic:
  enabled: true
  remote_configs: false
  health_check:
    enabled: true
    interval: 30s
  availability_check:
    enabled: true
    interval: 60s
  metadata_refresh:
    enabled: true
    interval: 30s
  cluster_settings_check:
    enabled: false
    interval: 20s

disk_queue:
  prepare_files_to_read: true
  #max_bytes_per_file: 20971520
  eof_retry_delay_in_ms: 500
  compress:
    delete_after_compress: true
    idle_threshold: 20

metrics:
  enabled: true
  queue: metrics
  instance:
    enabled: true
  network:
    enabled: true
    summary: true

badger:
  value_log_max_entries: 1000000
  value_log_file_size: 104857600
```

Configuration description:

```yaml
- name: async_bulk
  filter:
    - bulk_reshuffle:
        when:
          contains:
            _ctx.request.path: /_bulk
        elasticsearch: prod
        level: node
        partition_size: 1
        #shards: [1,3,5,7,9,11,13]
        continue_metadata_missing: true
        fix_null_id: true
    - http:
        schema: "https" #https or http
        hosts:
          - "165ed1e903914b929746c642d92b5a21.192.168.200.209.ip.es.a:9243"
          - "165ed1e903914b929746c642d92b5a21.192.168.200.209.ip.es.b:9243"
          - "165ed1e903914b929746c642d92b5a21.192.168.200.209.ip.es.c:9243"
```

- The request first passes through the 'bulk_reshuffle' filter. If the buffer is submitted successfully, the request returns 200 and the data is queued for consumption. If the buffer is submitted unsuccessfully, the request enters the 'http' filter and is sent directly to ECE Proxy.

After testing and verification, the write performance increased by 20% after the transformation.

For more configuration information about the INFINI Gateway, please refer to the [official website](https://infinilabs.cn/docs/latest/gateway/).

## About the INFINI Gateway

![](http://infinilabs.cn/img/blog/banner/gateway_banner@2x.png)

The INFINI Gateway is a high performance gateway for Elasticsearch. It offers a broad range of features and is easy to use. 
The INFINI Gateway works in the same way as a common reverse proxy. It is usually deployed in front of Elasticsearch clusters. All requests are sent to the gateway instead of Elasticsearch, and then the gateway forwards the requests to the back-end Elasticsearch clusters. The gateway is deployed between the client and Elasticsearch. Therefore, the gateway can be configured to perform index-level traffic control and throttling, cache acceleration for common queries, query request audit, and dynamic modification of query results.

The INFINI Gateway has been open-sourced now (https://github.com/infinilabs/gateway). If you have any related questions or suggestions, you are welcome to submit PRs or Issues and join in the open-source co-construction together!
