### ISSUE TITLE
INFINI Gateway Case Sharing - Use The INFINI Gateway to implement multi-cluster writes

### ISSUE THREAD

**Issue by liukuijun666** [liukuijun666/Blog#4]
## Background
 
The amount of cluster data increases by 3 TB per day. To avoid performance problems caused by a single cluster being too large, we plan to write data to multiple clusters.

## Solution

Clusters can be divided according to the time when the data was generated, such as by month, to ensure that a single cluster is within a controllable range.

To make data access as seamless as possible for applications, you can use the INFINI Gateway to split traffic in the front end, and use the 'context_switch' filter to make conditional judgments on matching context variables to split traffic into different clusters.

### Split Traffic

The data is split according to the writing time of the current data. For example, the data on the 1st, 4th, 7th, 10th, 13th, 16th, 19th, 22nd, 25th, 28th, and 31st of each month is written to the es1 cluster; the data on the 2nd, 5th, 8th, 11th, 14th, 17th, 20th, 23rd, 26th, and 29th of each month is written to the es2 cluster; the data on the 3rd, 6th, 9th, 12th, 15th, 18th, 21st, 24th, 27th, and 30th of each month is written to the es3 cluster.

Note: The current solution only divides traffic based on a relatively coarse granularity, not the document and field granularity. There may be errors in the boundary time of the two division granularities. For example, between 1 and 2, there may be a log record number that is actually generated at the bottom of 1, but is saved in the write cluster of 2 data due to time index delay.

### INFINI Gateway Configuration

```yaml
entry:
  - name: test_entry
    enabled: true
    router: default
    max_concurrency: 20000
    network:
      binding: 0.0.0.0:8000

router:
  - name: default
    default_flow: default_flow

flow:
  - name: not_found
    filter:
      - elasticsearch:
          elasticsearch: es1
  - name: es1
    filter:
      - elasticsearch:
          elasticsearch: es1
  - name: es2
    filter:
      - elasticsearch:
          elasticsearch: es2
  - name: es3
    filter:
      - elasticsearch:
          elasticsearch: es3

  - name: default_flow
    filter:
      - context_switch:
          context: _sys.day_of_now
          default_flow: not_found
          skip_error: true
          switch:
            - case: [1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31]
              case_value_type: int
              action: redirect_flow
              flow: es1
            - case: [2, 5, 8, 11, 14, 17, 20, 23, 26, 29]
              case_value_type: int
              action: redirect_flow
              flow: es2
            - case: [3, 6, 9, 12, 15, 18, 21, 24, 27, 30]
              case_value_type: int
              action: redirect_flow
              flow: es3

elasticsearch:
  - name: es1
    enabled: true
    endpoints:
     - http://10.247.146.51:32255
    basic_auth:
      username: infini
      password: infiniinfini
  - name: es2
    enabled: true
    endpoints:
     - http://10.247.146.51:32188
    basic_auth:
      username: infini
      password: infiniinfini
  - name: es3
    enabled: true
    endpoints:
     - http://10.247.146.51:32091
    basic_auth:
      username: infini
      password: infiniinfini
```

other context variables available are:

- _sys.month_of_now
- _sys.weekday_of_now
- _sys.day_of_now
- _sys.hour_of_now
- _sys.minute_of_now
- _sys.second_of_now

For more configuration information about the INFINI Gateway, please refer to the [official website](https://infinilabs.cn/docs/latest/gateway/).

## About the INFINI Gateway

![](http://infinilabs.cn/img/blog/banner/gateway_banner@2x.png)

The INFINI Gateway is a high performance gateway for Elasticsearch. It offers a broad range of features and is easy to use. 
The INFINI Gateway works in the same way as a common reverse proxy. It is usually deployed in front of Elasticsearch clusters. All requests are sent to the gateway instead of Elasticsearch, and then the gateway forwards the requests to the back-end Elasticsearch clusters. The gateway is deployed between the client and Elasticsearch. Therefore, the gateway can be configured to perform index-level traffic control and throttling, cache acceleration for common queries, query request audit, and dynamic modification of query results.

The INFINI Gateway has been open-sourced now (https://github.com/infinilabs/gateway). If you have any related questions or suggestions, you are welcome to submit PRs or Issues and join in the open-source co-construction together!
